name: Docker Image CI



jobs:
  build:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - name: Set Timestamp Variable
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag triton-docker:$TIMESTAMP
    - name: Run test cases
      run: docker run --entrypoint /bin/bash --rm triton-docker:$TIMESTAMP -c 'ctest --test-dir /tmp/triton-build/ --output-on-failure'
